[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nsv"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
mysave = "modules.scripts.mysave:main"
myrun  = "modules.scripts.myrun:main"
mymesh = "modules.scripts.mesh_stats:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["modules*"]