[pytest]
pythonpath = .

testpaths = 
    unit_tests

addopts = --strict-markers -v

markers =
    slow: marks heavy MMS
    mpi: marks tests that must be run using mpiexec

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning