solver_parameters:
  snes_type: ksponly
  snes_max_it: 50
  snes_rtol: 1e-6

  ksp_type: fgmres
  ksp_max_it: 50
  ksp_rtol: 1e-6
  ksp_atol: 1e-12

  pc_type: fieldsplit
  pc_fieldsplit_type: schur
  pc_fieldsplit_schur_fact_type: lower
  pc_fieldsplit_schur_precondition: selfp

  # velocity block
  fieldsplit_0_ksp_type: cg        # instead of preonly
  fieldsplit_0_pc_type: hypre
  fieldsplit_0_pc_hypre_type: boomeramg
  fieldsplit_0_ksp_rtol: 1e-4     # relaxed tolerance
  fieldsplit_0_ksp_max_it: 20     # enough for first CN step

  # pressure block
  fieldsplit_1_ksp_type: preonly
  fieldsplit_1_pc_type: jacobi

