solver_parameters:
  mat_type: matfree
  snes_monitor: null
  
  ksp_type: fgmres
  ksp_gmres_modifiedgramschmidt: null
  ksp_monitor_true_residual: null

  pc_type: fieldsplit
  pc_fieldsplit_type: schur
  pc_fieldsplit_schur_fact_type: lower

  # --- Velocity block ---
  fieldsplit_0_ksp_type: preonly
  fieldsplit_0_pc_type: hypre
  fieldsplit_0_pc_hypre_type: boomeramg

  # --- Pressure block ---
  fieldsplit_1_ksp_type: preonly
  fieldsplit_1_pc_type: hypre
  fieldsplit_1_pc_hypre_type: boomeramg