solver_parameters:
  mat_type: aij #matfree
  
  snes_monitor: null
  snes_type: newtonls
  snes_linesearch_type: bt
  snes_rtol: 1e-4
  snes_max_it: 5

  ksp_type: fgmres
  ksp_gmres_modifiedgramschmidt: null
  ksp_monitor_true_residual: null
  ksp_rtol: 1e-2
  ksp_max_it: 50

  pc_type: fieldsplit
  pc_fieldsplit_type: schur
  pc_fieldsplit_schur_fact_type: lower

  fieldsplit_0_ksp_type: preonly
  fieldsplit_0_pc_type: python
  fieldsplit_0_pc_python_type: firedrake.AssembledPC
  fieldsplit_0_assembled_pc_type: hypre
  fieldsplit_0_assembled_pc_hypre_type: boomeramg
  fieldsplit_0_assembled_pc_hypre_boomeramg_relax_type_all: symmetric-SOR/Jacobi
  fieldsplit_1_pcd_Mp_pc_hypre_boomeramg_relax_type_all: symmetric-SOR/Jacobi

  fieldsplit_1_ksp_type: fgmres
  fieldsplit_1_ksp_rtol: 1e-2
  fieldsplit_1_ksp_max_it: 10
  fieldsplit_1_pc_type: python
  fieldsplit_1_pc_python_type: firedrake.PCDPC

  fieldsplit_1_pcd_Mp_pc_type: hypre
  fieldsplit_1_pcd_Mp_pc_hypre_type: boomeramg
  fieldsplit_1_pcd_Mp_ksp_type: preonly

  fieldsplit_1_pcd_Kp_ksp_type: preonly
  fieldsplit_1_pcd_Kp_pc_type: hypre

  #fieldsplit_1_pcd_Fp_mat_type: matfree

  fieldsplit_1_pcd_u: velocity
  fieldsplit_1_pcd_dt: "{dt}"
