solver_parameters:
  mat_type: matfree

  ksp_type: fgmres
  ksp_monitor_short: null

  pc_type: fieldsplit
  pc_fieldsplit_type: schur
  pc_fieldsplit_schur_fact_type: lower

  fieldsplit_0_ksp_type: preonly
  fieldsplit_0_pc_type: python
  fieldsplit_0_pc_python_type: firedrake.AssembledPC
  fieldsplit_0_assembled_pc_type: hypre
  fieldsplit_0_assembled_pc_hypre_type: boomeramg

  fieldsplit_1_ksp_type: preonly  
  fieldsplit_1_ksp_rtol: 1e-3
  fieldsplit_1_ksp_max_it: 20
  fieldsplit_1_pc_type: hypre
  fieldsplit_1_pc_hypre_type: boomeramg
