t0: 0.0             # initial time
T: 0.01              # final time
dt: 0.01            # time step
theta: 0.5          # theta constant
gamma: 2.0          # grad-div stabilization constant
Re: 600.0           # Reynold's num: 1/viscostiy
G: 50.0             # initial pressure gauge
P: -20.0            # pressure strength (P*x + G)