t0: 0.0             # initial time
T: 5.0              # final time
dt: 0.001           # time-step
theta: 0.5          # theta constant
gamma: 2.0          # grad-div stabilization constant
Re: 600.0           # Reynold's num: 1/viscostiy
G: 0.0              # initial pressure gauge
P: -1.0             # pressure strength (P*x + G)

solver: "BDF2"      # valid:  "BDF2" (Backward Differentiation) or 
                    #         "CN" (Crank-Nicolson)
elements: "TH"      # valid:  "SV" (Scott Vogelius - requires barycentric refinement) or 
                    #         "TH" (Taylor Hood)
views: "None"       # valid:  "Full" for debugging by viewing ALL solver parameters, 
                    #         "Some" for debugging by monitoring subprocesses like KSP, 
                    #         "None" for no debugging

char_length: 1.0    # characteristic length: use for bluff bodies, airfoils, etc.

# probe: points to evaluate energy spectrum at, assuming Taylor's frozen flow hyp.
# probe types to copy-paste
# step: [[4.8, 1, 0], [4.9, 1.1, 0], [4.7, 0.9, 0], [4.8, 2, 0], [4.9, 2.1, 0], [4.7, 2.9, 0], [6, 2, 0], [6, 1.5, 0], [4.7, 0.9, 0], [10, 1.5, 0], [11, 2, 0], [12, 2, 0], [13, 2.5, 0], [14, 3, 0], [15, 2.5, 0]]

probes: [[4.8, 1, 0], [4.9, 1.1, 0], [4.7, 0.9, 0], [4.8, 2, 0], [4.9, 2.1, 0], [4.7, 2.9, 0], [6, 2, 0], [6, 1.5, 0], [4.7, 0.9, 0], [10, 1.5, 0], [11, 2, 0], [12, 2, 0], [13, 2.5, 0], [14, 3, 0], [15, 2.5, 0]] 