t0: 0.0             # initial time
T: 1.0             # final time
dt: 0.001           # time step
theta: 0.5          # theta constant
gamma: 0.0          # grad-div stabilization constant
Re: 600.0           # Reynold's num: 1/viscostiy
G: 0.0              # initial pressure gauge
P: -1.0             # pressure strength (P*x + G)

solver: "BDF2"      # valid:  "BDF2" (Backward Differentiation) or 
                    #         "CN" (Crank-Nicolson)
elements: "SV"      # valid:  "SV" (Scott Vogelius - requires barycentric refinement) or 
                    #         "TH" (Taylor Hood)
views: "None"       # valid:  "Full" for debugging by viewing ALL solver parameters, 
                    #         "Some" for debugging by monitoring subprocesses like KSP, 
                    #         "None" for no debugging