name: Nightly Unit Tests

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  mms_tests:
    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python deps
        run: |
          pip install pytest matplotlib pyyaml

      - name: Install project
        run: pip install -e .

      - name: Run unit tests
        run: |
          pytest tests/unit -v --maxfail=1